name: Test YTDL

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0/12 * * *" # 7:30AM/PM EST, 8:30AM/PM EDT

jobs:
  test-ytdl:
    name: Test YTDL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install Node.js dependencies
        run: npm ci
        env:
          ASCOPE_NO_FFMPEG: true
      - name: Test YTDL
        run: npm run test-ytdl
